"""Determinism and portability tests for the reproducible benchmark harness.

Locks down the behavior of benchmarks/reproducible.py: volatile-field
normalization, checkout-path-independent content hashing, the strict-gcc
compile gate, and baseline verification. All extraction exercises run against
tiny synthetic corpora in tmp_path; the real repo tree is never touched.
"""

from __future__ import annotations

import copy
import hashlib
import json
import os
import re
import shutil
import subprocess

import pytest
from pathlib import Path

import benchmarks.reproducible as reproducible
from benchmarks.reproducible import (
    CompileStats,
    EnvironmentFingerprint,
    ExtractionStats,
    HarnessReport,
)

NEEDS_GCC = pytest.mark.skipif(shutil.which("gcc") is None, reason="gcc not available on this host")

STABLE_C_BODY = (
    "int add_arrays(const double *restrict a, const double *restrict b,\n"
    "               double *restrict c, int n) {\n"
    "    for (int i = 0; i < n; i++) {\n"
    "        c[i] = a[i] + b[i];\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
)

CORPUS_K1 = "import numpy as np\n\n\ndef add_arrays(a, b):\n    return np.add(a, b)\n"
CORPUS_K2 = "import numpy as np\n\n\ndef sub_arrays(a, b):\n    return np.subtract(a, b)\n"


def _write_corpus(corpus: Path) -> None:
    corpus.mkdir(parents=True, exist_ok=True)
    (corpus / "k1.py").write_text(CORPUS_K1, encoding="utf-8")
    (corpus / "k2.py").write_text(CORPUS_K2, encoding="utf-8")


def _origin_offsets(out_dir: Path) -> list[tuple[str, str]]:
    offsets = []
    for c in sorted(out_dir.glob("*.c")):
        match = re.search(r"ORIGIN FILE:.*:(\d+)\s*$", c.read_text(encoding="utf-8"), re.MULTILINE)
        offsets.append((c.name, match.group(1) if match else "missing"))
    return offsets


def _make_report(content_sha256: str = "abcd" * 8) -> HarnessReport:
    fingerprint = EnvironmentFingerprint(
        python_version="3.13.14",
        numpy_version="2.3.0",
        gcc_version="gcc (GCC) 13.2.0",
        platform="Linux",
        cpu_count=8,
        git_commit="c7faa6b",
        purce_version="0.1.0",
    )
    corpus = ExtractionStats(
        corpus_dir="benchmarks/corpus",
        py_files=2,
        c_files=2,
        h_files=1,
        prov_files=2,
        error_directives=0,
        unresolved_files=0,
        total_c_lines=82,
    )
    return HarnessReport(
        seed=42,
        fingerprint=fingerprint,
        corpora=[corpus],
        compile_total=2,
        compile_passed=2,
        compile_failed=0,
        compile_failures=[],
        content_sha256=content_sha256,
        total_c_files=2,
        total_py_files=2,
        timestamp_utc="2026-08-06T00:00:00Z",
    )


class TestNormalizeContent:
    def test_strips_generated_at_header_line(self) -> None:
        text = (
            "/*\n"
            " * GENERATED BY:     purce v0.1.0\n"
            " * GENERATED AT:     2026-08-06T20:13:56Z\n"
            " */\n" + STABLE_C_BODY
        )
        normalized = reproducible._normalize_content(text)
        assert "GENERATED AT" not in normalized
        assert "GENERATED BY" in normalized
        assert STABLE_C_BODY in normalized

    def test_strips_generated_at_json_field(self) -> None:
        text = (
            '{"generated_at": "2026-08-06T20:13:56Z", "source": "x.py", '
            '"ir_node": {"algorithm": "element_add"}}\n'
        )
        normalized = reproducible._normalize_content(text)
        assert "generated_at" not in normalized
        assert '"source": "x.py"' in normalized
        assert '"algorithm": "element_add"' in normalized

    def test_replaces_checkout_root_with_placeholder(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(reproducible, "_CHECKOUT_ROOT", "/home/ci/checkouts/purce")
        text = (
            "ORIGIN FILE: /home/ci/checkouts/purce/benchmarks/corpus/matmul.py:12\n"
            "SOURCE FILE: /opt/shared/deps/helper.py\n"
        )
        normalized = reproducible._normalize_content(text)
        assert normalized == (
            "ORIGIN FILE: {PURCE_ROOT}/benchmarks/corpus/matmul.py:12\n"
            "SOURCE FILE: /opt/shared/deps/helper.py\n"
        )

    def test_stable_content_unchanged(self) -> None:
        assert reproducible._normalize_content(STABLE_C_BODY) == STABLE_C_BODY


class TestContentHash:
    def test_identical_dirs_hash_equal(self, tmp_path: Path) -> None:
        dir_a = tmp_path / "a"
        dir_b = tmp_path / "b"
        for d in (dir_a, dir_b):
            d.mkdir()
            (d / "kernel.c").write_text(STABLE_C_BODY, encoding="utf-8")
        assert reproducible.content_hash(dir_a) == reproducible.content_hash(dir_b)

    def test_one_byte_difference_changes_hash(self, tmp_path: Path) -> None:
        dir_a = tmp_path / "a"
        dir_b = tmp_path / "b"
        for d in (dir_a, dir_b):
            d.mkdir()
            (d / "kernel.c").write_text(STABLE_C_BODY, encoding="utf-8")
        (dir_b / "kernel.c").write_text(
            STABLE_C_BODY.replace("a[i] + b[i]", "a[i] - b[i]"), encoding="utf-8"
        )
        assert reproducible.content_hash(dir_a) != reproducible.content_hash(dir_b)

    def test_matches_hand_computed_sha256(self, tmp_path: Path) -> None:
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        (out_dir / "kernel.c").write_text(STABLE_C_BODY, encoding="utf-8")
        hasher = hashlib.sha256()
        hasher.update(b"kernel.c\x00")
        hasher.update(reproducible._normalize_content(STABLE_C_BODY).encode("utf-8"))
        hasher.update(b"\x00")
        digest = reproducible.content_hash(out_dir)
        assert digest == hasher.hexdigest()
        assert re.fullmatch(r"[0-9a-f]{64}", digest)


class TestCompileGate:
    def test_jobs_zero_raises_value_error(self, tmp_path: Path) -> None:
        with pytest.raises(ValueError, match="jobs"):
            reproducible.run_compile_gate(tmp_path, jobs=0)

    @NEEDS_GCC
    def test_scores_successes_and_failures(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        for name in ("good_a.c", "good_b.c", "bad.c"):
            (out_dir / name).write_text("int x;\n", encoding="utf-8")

        def fake_compile_one(args: tuple[str, str]) -> tuple[str, str, bool, str]:
            c_path, gcc = args
            if Path(c_path).name == "bad.c":
                return c_path, gcc, False, "error: 'nope' undeclared"
            return c_path, gcc, True, ""

        monkeypatch.setattr(reproducible, "_compile_one", fake_compile_one)
        stats = reproducible.run_compile_gate(out_dir, jobs=2)
        assert stats.total == 3
        assert stats.passed == 2
        assert stats.failed == 1
        assert stats.failures == [("bad.c", "error: 'nope' undeclared")]
        assert not stats.all_passed()

    @NEEDS_GCC
    def test_end_to_end_gate_passes_synthetic_corpus(self, tmp_path: Path) -> None:
        corpus = tmp_path / "src"
        out_dir = tmp_path / "out"
        _write_corpus(corpus)
        reproducible.run_extraction(corpus, out_dir)
        stats = reproducible.run_compile_gate(out_dir, jobs=2)
        assert stats.passed == stats.total
        assert stats.failed == 0
        assert stats.failures == []
        assert stats.all_passed()
        assert isinstance(stats, CompileStats)


class TestRunExtraction:
    def test_counts_and_cmake(self, tmp_path: Path) -> None:
        corpus = tmp_path / "src"
        out_dir = tmp_path / "out"
        _write_corpus(corpus)
        stats = reproducible.run_extraction(corpus, out_dir)
        assert stats.corpus_dir == str(corpus)
        assert stats.py_files == 2
        assert stats.c_files == 2
        assert stats.prov_files == stats.c_files
        assert stats.h_files == 1
        assert stats.error_directives == 0
        assert stats.unresolved_files == 0
        assert stats.total_c_lines > 0
        assert len(list(out_dir.glob("CMakeLists.txt"))) == 1

    @NEEDS_GCC
    def test_generated_c_compiles_strictly(self, tmp_path: Path) -> None:
        corpus = tmp_path / "src"
        out_dir = tmp_path / "out"
        _write_corpus(corpus)
        reproducible.run_extraction(corpus, out_dir)
        gcc = shutil.which("gcc")
        for c in sorted(out_dir.glob("*.c")):
            result = subprocess.run(
                [
                    gcc,
                    "-std=c99",
                    "-O2",
                    "-Wall",
                    "-Wextra",
                    "-pedantic",
                    "-c",
                    str(c),
                    "-o",
                    os.devnull,
                ],
                capture_output=True,
                text=True,
                timeout=120,
            )
            assert result.returncode == 0, c.name + "\n" + result.stderr


class TestBaselineVerification:
    def test_matching_baseline_passes(self) -> None:
        report = _make_report()
        assert reproducible.verify_against_baseline(report, report.to_dict()) == []

    def test_mismatched_content_hash_reports_deviation(self) -> None:
        report = _make_report()
        baseline = copy.deepcopy(report.to_dict())
        other_hash = "deadbeef" * 8
        baseline["content_sha256"] = other_hash
        deviations = reproducible.verify_against_baseline(report, baseline)
        assert deviations == [f"content_sha256 {other_hash} != {report.content_sha256}"]

    def test_missing_keys_produce_none_deviations(self) -> None:
        report = _make_report()
        deviations = reproducible.verify_against_baseline(
            report, {"content_sha256": report.content_sha256}
        )
        assert "compile.total None != 2" in deviations
        assert "compile.failed None != 0" in deviations
        assert "totals.c_files None != 2" in deviations
        assert "corpus count differs" in deviations

    def test_corpus_c_file_mismatch_reported(self) -> None:
        report = _make_report()
        baseline = copy.deepcopy(report.to_dict())
        baseline["corpora"][0]["c_files"] = 99
        deviations = reproducible.verify_against_baseline(report, baseline)
        assert any("c_files 99 != 2" in d for d in deviations)

    def test_corrupted_baseline_json_raises(self, tmp_path: Path) -> None:
        bad = tmp_path / "baseline.json"
        bad.write_text("{not valid json", encoding="utf-8")
        with pytest.raises(json.JSONDecodeError):
            reproducible.load_baseline(bad)


class TestPortabilityAcrossCheckouts:
    def test_content_hash_equal_after_checkout_root_normalization(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        checkout_a = tmp_path / "copya" / "corpus"
        checkout_b = tmp_path / "copyb" / "corpus"
        _write_corpus(checkout_a)
        _write_corpus(checkout_b)

        out_a = tmp_path / "out_a"
        out_b = tmp_path / "out_b"
        reproducible.run_extraction(checkout_a, out_a)
        reproducible.run_extraction(checkout_b, out_b)

        assert sorted(p.name for p in out_a.glob("*.c")) == sorted(
            p.name for p in out_b.glob("*.c")
        )
        assert _origin_offsets(out_a) == _origin_offsets(out_b)

        raw_a = reproducible.content_hash(out_a)
        raw_b = reproducible.content_hash(out_b)
        assert raw_a != raw_b

        monkeypatch.setattr(
            reproducible, "_CHECKOUT_ROOT", str(checkout_a.parent).replace("\\", "/")
        )
        normalized_a = reproducible.content_hash(out_a)
        monkeypatch.setattr(
            reproducible, "_CHECKOUT_ROOT", str(checkout_b.parent).replace("\\", "/")
        )
        normalized_b = reproducible.content_hash(out_b)
        assert normalized_a == normalized_b

    def test_load_baseline_round_trip(self, tmp_path: Path) -> None:
        baseline_path = tmp_path / "baseline.json"
        baseline_path.write_text(
            json.dumps({"seed": 42, "content_sha256": "abc"}), encoding="utf-8"
        )
        loaded = reproducible.load_baseline(baseline_path)
        assert loaded == {"seed": 42, "content_sha256": "abc"}


class TestHashSeedIndependence:
    """Extraction output must be byte-identical regardless of PYTHONHASHSEED.

    Regression test for the pre-v0.1-beta non-determinism: the builder stored
    caller->callee edges in a plain set and iterated them unsorted, so emitted
    ``nested_deps`` (and generated provenance) varied process-to-process. The
    builder now iterates callees in sorted order, so generated output is
    byte-reproducible across processes and machines.
    """

    def test_extraction_is_hash_seed_independent(self, tmp_path: Path) -> None:
        import subprocess
        import sys

        corpus = tmp_path / "src"
        _write_corpus(corpus)
        out_a = tmp_path / "out_a"
        out_b = tmp_path / "out_b"
        root = Path(__file__).resolve().parents[1]
        for seed, out in (("1", out_a), ("2", out_b)):
            r = subprocess.run(
                [sys.executable, "-m", "purce.cli", "extract", str(corpus), "-o", str(out)],
                cwd=root,
                capture_output=True,
                text=True,
                timeout=600,
                env={"PYTHONHASHSEED": seed, **{k: v for k, v in __import__("os").environ.items()}},
            )
            assert r.returncode == 0, r.stderr[-500:]
        hash_a = reproducible.content_hash(out_a)
        hash_b = reproducible.content_hash(out_b)
        assert hash_a == hash_b
